kind: workload
metadata:
  namespace: default
  name: workload
description: workload
apiVersion: cpln.io/v1
org: kyle-test-org
gvc: fresh
tags: {}
spec:
  type: serverless
  containers:
    - name: agent
      cpu: 50m
      env:
        - name: SECRET_KEY
          value: cpln://secret/secret.payload
      image: kylecupp/agent:0.9.3
      inheritEnv: false
      memory: 128Mi
      ports:
        - number: 8080
          protocol: http
  defaultOptions:
    autoscaling:
      maxConcurrency: 1000
      maxScale: 3
      metric: concurrency
      minScale: 1
      scaleToZeroDelay: 300
      target: 100
    capacityAI: true
    debug: false
    suspend: false
    timeoutSeconds: 5
  firewallConfig:
    external:
      inboundAllowCIDR:
        - 0.0.0.0/0
      inboundBlockedCIDR: []
      outboundAllowCIDR: []
      outboundAllowHostname: []
      outboundAllowPort: []
      outboundBlockedCIDR: []
    internal:
      inboundAllowType: none
      inboundAllowWorkload: []
  identityLink: //gvc/fresh/identity/identity
  loadBalancer:
    direct:
      enabled: true
      ipSet: "/org/kyle-test-org/ipset/ipset"
      ports: [
        {
          externalPort: 443,
          protocol: "TCP",
          containerPort: 8080
        }
      ]
  supportDynamicTags: false
